---

- name: onyx_config_main
  hosts: ONYX
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    local_ip: 
    local_user: "root"
    local_pass: "3tango"
    ansible_network_os: onyx
    path: 
    type:
    del_all_first: "no"
    transfer_protocol: scp
    temp_time: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
  remote_user: admin

  tasks:

    - name: delete all config in the first place
      when: del_all_first == "yes"
      onyx_config:
         lines:
          - configuration new {{ temp_time }} factory keep-connect
          - configuration switch-to {{ temp_time }} no-reboot
          - username admin password admin
          - username monitor password monitor
          - configuration write
          - reload force
      ignore_errors: yes
   
    - name: wait for connection
      wait_for:
         host: "{{ inventory_hostname }}"
         port: 22
         delay: 160
         timeout: 800
      become: false
      tags: wait_for_ssh



    - name: fetch text configuration file
      when: type == "text"
      onyx_config:
          src:  "{{ path }}"

    - name: fetch and apply binary configuration file 
      when: type == "bin"
      onyx_config:
         lines:
          - configuration delete {{ path | basename }}
          - configuration fetch scp://{{local_user}}:{{local_pass}}@{{local_ip}}/{{ path }}
          - configuration switch-to {{ path | basename }} no-reboot
      ignore_errors: yes

