---

- name: onyx_config_main
  hosts: ONYX
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    local_ip: 
    local_user: root
    local_pass: 3tango
    ansible_network_os: onyx
    path: 
    type:
    del_all_first: "no"
    transfer_protocol: scp
    temp_time: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
  remote_user: admin

  tasks:

    - name: delete all config in the first place
      when: del_all_first == "yes"
      onyx_config:
         lines:
          - configuration new {{ temp_time }} factory keep-connect
          - configuration switch-to {{ temp_time }} no-reboot
          - username admin password admin
          - username monitor password monitor
          - configuration write
          - reload force
      ignore_errors: yes
   
    - name: sleep for 180 seconds and continue with play
      wait_for:
        timeout: 180
      delegate_to: localhost

    - name: apply text configuration file
      when: type == "text"
      onyx_config:
          src:  "{{ path }}"

    - name: fetch and apply binary configuration file 
      onyx_config:
         lines:
          - configuration fetch scp://{{ local_user }}:{{ local_pass }}@{{ local_ip }}/{{ path }}



 #   - name: copy binary configuration file
 #     net_put:
 #         dest: "/config/db/"
 #         mode: binary
 #         protocol: "{{ transfer_protocol }}" 
 #         src: "{{ path }}"
 #     when: type == "bin"
